#
# Base settings for Arch
#
#

- name: Install Arch Pacman file
  copy: src=pacman.conf dest=/etc/ owner=root mode=0644

# - name: Arch refresh keys
#   command: pacman-key --refresh-keys

#- name: Refresh database
#  shell: pacman -Fy

# - name: Upgrade system
#   pacman:
#     update_cache: yes
#     upgrade: yes

# - name: Install Yaourt
#   pacman: name=yaourt state=present update_cache=yes

- name: Install Pacaur
  pacman: name=pacaur state=present update_cache=yes

- name: Install defaults packages
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
   - bash-completion
   - dhclient
   - openssh
   - man-db
   - wget
   - curl
   - dunst
   - ngrep
   - tree
   - git
   - gnupg
   - tig
   - unzip
   - logrotate
   - rsyslog
   - sysstat
   - tmux
   - mlocate
   - bind-tools
   - termite
   - terminator
   - feh
   - ncdu
   - ccze

- name: Install X
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - libglvnd
    - xorg-server
    - xorg-xinit
    - slim
    - slim-themes
    - archlinux-themes-slim
    # - lxdm
    # - lxdm-gtk3
    - sddm
    - lightdm

# - name: Install sddm themes
#   become: false
#   command: 'yaourt -S --noconfirm --needed archlinux-themes-sddm'

# - name: Install lxdm themes
#   become: false
#   command: 'yaourt -Sy --noconfirm lxdm-themes'

- name: Install themes
  # command: "pacaur -S {{item.package}}" # creates={{item.creates}}"
  # with_items:
  #   # - { package: vertex-themesvertex-themes} #, creates: /usr/share/themes/Vertex }
  #   # - { package: adapta-gtk-theme} #, creates: /usr/share/themes/Adapta}
  #   - { package: gtk-theme-arc-git} #, creates: /usr/share/themes/
  # become: false
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - arc-gtk-theme
    - adapta-gtk-theme

- name: Install Python tools
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - python-pip
    - python2-pip
    - python-pylint
    - python2-pylint
    - python-pycurl
    - python2-pycurl

- name: Install Ruby
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - ruby

# - name: Install cronie
#   pacman: name=cronie state=present

# - name: Enable cronie service
#   service: name=cronie enabled=yes state=restarted

- name: Install Torrent tools
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - transmission-gtk
    - rtorrent

- name: Install ChangeLog
  copy: src=ChangeLog dest=/etc/ owner=root mode=0644

- name: Install motd
  copy: src=motd dest=/etc/ owner=root mode=0644
