- name: Install default packages
  yum: name={{ item }} state=present
  with_items:
    - openssh
    - wget
    - curl
    - net-tools
    - ngrep
    - tree
    - git
    - gnupg
    - tig
    - unzip
    - rsyslog
    - tmux
    # - termite
    - terminator
    # - feh

- name: Install X
  yum: name={{ item }} state=present
  with_items:
    - xorg-x11-server-Xorg
    - xorg-x11-xinit
    - xterm
    - terminus-fonts
    - lightdm
