- name: Check if EPEL repo is already configured.
  stat: path="/etc/yum.repos.d/epel.repo"
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Check if Nux-Desktop repo is already configured.
  stat: path="/etc/yum.repos.d/nux-dextop.repo"
  register: nux_repofile_result

- name: Install Nux-Desktop repo.
  yum:
    name: "http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el{{ ansible_distribution_major_version }}.nux.noarch.rpm"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not nux_repofile_result.stat.exists

- name: Import Nux-Desktop GPG key.
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-nux.ro"
    state: present
  when: not nux_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install default packages
  yum: name={{ item }} state=present
  with_items:
    - openssh
    - wget
    - curl
    - net-tools
    - ngrep
    - tree
    - git
    - gnupg
    - tig
    - unzip
    - rsyslog
    - tmux
    # - termite
    - terminator
    # - feh

- name: Install X
  yum: name={{ item }} state=present
  with_items:
    - xorg-x11-server-Xorg
    - xorg-x11-xinit
    - xterm
    - terminus-fonts
    - lightdm

- name: Install torrent tools
  yum: name={{ item }} state=present
  with_items:
    - transmission-gtk
    - rtorrent
