#
# Base settings for Debian
#
#
- name: Install shell tools
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
   - bash-completion
   - tree
   - tmux
   - ncdu

- name: Install terminal emulators
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - termite
    - terminator

- name: Install defaults packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
#    - man-db
#    - apt-file
    - wget
    - curl
    - ngrep
    - bash-completion
    - git
    - unzip
    - logrotate
    - rsyslog

- name: Install Python tools
  apt: pkg={{ item }} state=present
  with_items:
    - python-pip
    - pylint
    - python-pycurl

- name: Install torrent tools
  apt: pkg={{ item }} state=present
  with_items:
    - transmission-gtk
    - rtorrent

- name: Install ChangeLog
  copy: src=ChangeLog dest=/etc/ owner=root mode=0644

- name: Install motd
  copy: src=motd dest=/etc/ owner=root mode=0644
