#
# Base settings for Linux Mint
#
#

- name: Install shell tools
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
   - bash-completion
   - tree
   - tmux
   - ncdu

- name: Install terminal emulators
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - terminator

- name: Install defaults packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
   - openssh-server
   - man-db
   - wget
   - curl
   - dunst
   - ngrep
   - git
   - gnupg
   - tig
   - unzip
   - logrotate
   - rsyslog
   - sysstat
   - mlocate
   - feh
   - ccze

- name: Install Torrent tools
  apt: pkg={{ item }} state=present
  with_items:
    - transmission-gtk
    - rtorrent

- name: Install ChangeLog
  copy: src=ChangeLog dest=/etc/ owner=root mode=0644

- name: Install motd
  copy: src=motd dest=/etc/ owner=root mode=0644
