- name: Create Applications directory
  command: mkdir /home/{{ user }}/Apps creates=/home/{{ user }}/Apps

- name: Create user binary directory
  command: mkdir /home/{{ user }}/bin creates=/home/{{ user }}/bin

- name: Install inputrc
  copy: src=inputrc dest=/home/{{ user }}/.inputrc
