- name: Install Emacs
  pacman:
    name: emacs
    state: present
    update_cache: yes

- name: Install Neovim
  pacman:
    name: neovim
    state: present
    update_cache: yes

# - name: VIM directory
#   action: file path=/home/{{ user }}/.vim state=directory

# - name: VIM Bundle directory
#   action: file path=/home/{{ user }}/.vim/bundle state=directory

# - name: VIM Vundle
#   git: repo=https://github.com/gmarik/vundle.git dest=/home/{{ user }}/.vim/bundle/vundle version=master
