- name: Install Cask
  command: python /tmp/cask.py creates=/home/$user/.cask

- name: Download Scame
  command: curl -fsSkL https://raw.github.com/nlamirault/scame/master/scame -o /tmp/scame

- name: Install Scame
  command: bash /tmp/scame
