- name: Emacs configuration files
  copy: src=files/emacs dest=/home/$user/.emacs

- name: Creates Emacs directory
  action: file path=/home/$user/.emacs.d state=directory

- name: Emacs .el files
  copy: src=$item dest=/home/$user/.emacs.d/
  with_fileglob:
    - files/*.el

- name: Cask file
  copy: src=files/Cask dest=/home/$user/.emacs.d/

- name: Creates Emacs themes directory
  action: file path=/home/$user/.emacs.d/themes state=directory

- name: Emacs theme
  copy: src=$item dest=/home/$user/.emacs.d/themes/
  with_fileglob:
    - files/themes/*.el

- name: Download Cask
  command: curl -fsSkL https://raw.github.com/cask/cask/master/go -o /home/$user/Apps/cask.py creates=/home/$user/.cask

- name: Install Cask
  command: python /home/$user/Apps/cask.py chdir=/home/$user/.emacs.d/ creates=/home/$user/.cask

- name: Configure Emacs using Cask
  command: /home/$user/.cask/bin/cask chdir=/home/$user/.emacs.d
