# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :divona do |divona_config|
    divona_config.vm.hostname = "DivonaArchDev"
    divona_config.vm.box = "nlamirault/archlinux"

    divona_config.vm.network :private_network, :ip => '10.10.2.33'
    divona_config.vm.network :forwarded_port, guest: 22, host: 8222

    divona_config.ssh.forward_agent = true
    divona_config.ssh.forward_x11 = true

    divona_config.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
      vb.name = "DivonaArchDev"
    end

    divona_config.vm.provision :ansible do |ansible|
      ansible.playbook = "../../ansible/divona.yml"
      ansible.inventory_path = "../../ansible/hosts/vagrant"
      ansible.limit = "all"
      #ansible.verbose = 'vvvv'
      ansible.host_key_checking = false
    end

  end

end
