# -*- mode: ruby -*-
# vi: set ft=ruby :

# Copyright (C) 2013-2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Vagrant.configure("2") do |config|

  config.vm.define :divona do |divona_config|
    divona_config.vm.hostname = "DivonaArchDev"
    divona_config.vm.box = "nlamirault/archlinux"

    divona_config.vm.network :private_network, :ip => '10.10.2.33'
    divona_config.vm.network :forwarded_port, guest: 22, host: 8222

    divona_config.ssh.forward_agent = true
    divona_config.ssh.forward_x11 = true

    divona_config.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
      vb.name = "DivonaArchDev"
    end

    divona_config.vm.provision :ansible do |ansible|
      ansible.playbook = "../../ansible/divona.yml"
      ansible.inventory_path = "../../ansible/hosts/vagrant"
      ansible.limit = "all"
      #ansible.verbose = 'vvvv'
      ansible.host_key_checking = false
    end

  end

end
