- name: Download Arduino
  get_url: url=https://downloads.arduino.cc/arduino-1.6.9-linux64.tar.xz dest=$HOME/Apps/arduino-1.6.9-linux64.tar.xz mode=0440

- name: Download Fritzing
  get_url: url=http://fritzing.org/media/downloads/fritzing-0.9.3b.linux.AMD64.tar.bz2 dest=$HOME/Apps/fritzing-0.9.3b.linux.AMD64.tar.bz2 mode=0440
