- stat: path=C:\Apps\arduino-1.6.9-windows.zip
  register: arduino_archive

- name: Download Arduino
  get_url: url=https://www.arduino.cc/download_handler.php?f=/arduino-1.6.9-windows.zip dest=C:\Apps\arduino-1.6.9-windows.zip mode=0440
  when: arduino_archive.stat is not defined

- stat: path=C:\Apps\fritzing-0.9.3b.linux.AMD64.tar.bz2
  register: fritzing_archive

- name: Download Fritzing
  get_url: url=http://fritzing.org/download/0.9.3b/windows-64bit/fritzing.0.9.3b.64.pc.zip dest=dest=C:\Apps\fritzing-0.9.3b.linux.AMD64.tar.bz2 mode=0440
  when: fritzing_archive.stat is not defined
