# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :ubuntu_dev do |ubuntu_config|
    ubuntu_config.vm.box = "trusty64"
    ubuntu_config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
    ubuntu_config.vm.hostname = "LamUbuntuDev"

    ubuntu_config.vm.network :private_network, :ip => '10.10.1.33'
    ubuntu_config.vm.network :forwarded_port, guest: 22, host: 8122

    ubuntu_config.ssh.forward_agent = true
    ubuntu_config.ssh.forward_x11 = true

    ubuntu_config.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
      vb.name = "LamUbuntuDev"
    end

    ubuntu_config.vm.provision :ansible do |ansible|
      ansible.playbook = "../../ansible/divona.yml"
      ansible.inventory_path = "../../ansible/hosts/vagrant"
      ansible.limit = "all"
      #ansible.verbose = 'vvvv'
      ansible.host_key_checking = false
    end

  end

end
