# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "trusty64"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.hostname = "LamUbuntu"
  config.vm.network :private_network, ip: "10.1.2.33"

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provider :virtualbox do |vb|
    #vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.name = "LamUbuntu"
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../../setup.yml"
    ansible.inventory_path = "../../ansible_hosts"
    ansible.verbose = '-vv'
  end

end
