# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :freebsd do |freebsd_config|
    freebsd_config.vm.box = "nlamirault/freebsd-10.3"

    freebsd_config.vm.hostname = "DivonaFreeBSDDev"
    freebsd_config.vm.network :private_network, :ip => '10.10.4.33'

    freebsd_config.ssh.insert_key = false
    # freebsd_config.ssh.private_key_path = "./vagrant.pub"
    freebsd_config.ssh.forward_agent = true
    freebsd_config.ssh.forward_x11 = true

    freebsd_config.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.name = "DivonaFreeBSDDev"
    end

    freebsd_config.vm.provision :ansible do |ansible|
      ansible.playbook = "../../ansible/divona.yml"
      ansible.inventory_path = "./host"
      ansible.limit = "all"
      ansible.verbose = 'vvvv'
      ansible.host_key_checking = false
    end

  end

end
