# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :freebsd do |freebsd_config|
    freebsd_config.vm.box = "FreeBSD10"
    freebsd_config.vm.box_url = "http://files.wunki.org/freebsd-10.0-amd64-wunki.box"

    freebsd_config.vm.hostname = "LamFreeBSDDev"
    freebsd_config.vm.network :private_network, :ip => '10.10.4.33'

    freebsd_config.ssh.forward_agent = true
    freebsd_config.ssh.forward_x11 = true

    config.vm.synced_folder "../", "/vagrant", :disabled => true

    freebsd_config.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.name = "LamFreeBSDDev"
    end

    freebsd_config.vm.provision :ansible do |ansible|
      ansible.playbook = "../../ansible/divona.yml"
      ansible.inventory_path = "../../ansible/hosts/vagrant"
      ansible.limit = "all"
      #ansible.verbose = 'vvvv'
      ansible.host_key_checking = false
    end

  end

end
