image: base
script:
    - sudo apt-add-repository ppa:rquillo/ansible
    - sudo apt-get update
    - sudo apt-get install ansible
    - sudo ansible-playbook --verbose -c local -i ansible/hosts/local ansible/divona.yml --extra-vars="user=ubuntu"
