# Copyright (C) 2013-2017 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

stages:
  - test
  - archlinux
  - debian

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

test:ansible:
  stage: test
  image: python:2.7
  script:
    - pip install ansible ansible-lint
    - ansible --version
    - for i in $(find ansible/ -name "*.yml"); do echo $i; ansible-lint $i; done

archlinux:build:
  stage: archlinux
  image: docker:git
  script:
    # - apk add --update build-base bash
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE_archlinux:latest" -f dockerfiles/Dockerfile.archlinux dockerfiles
    - docker push "$CI_REGISTRY_IMAGE_archlinux:latest"
  only:
    - master
    - develop

archlinux:test:
  stage: archlinux
  image: docker:git
  script:
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
    - docker run --rm -i -v ~/.ssh/id_rsa:/root/.ssh/id_rsa -v ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub -v `pwd`/ansible:/ansible/playbooks "$CI_REGISTRY_IMAGE_archlinux:latest" ansible-playbook -vvv -c local -i /ansible/playbooks/hosts/local /ansible/playbooks/divona.yml --extra-vars="user=root"
  only:
    - master
    - develop

debian:build:
  stage: debian
  image: docker:git
  script:
    # - apk add --update build-base bash
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE_debian:latest" -f dockerfiles/Dockerfile.debian dockerfiles
    - docker push "$CI_REGISTRY_IMAGE_debian:latest"
  only:
    - master
    - develop

debian:test:
  stage: debian
  image: docker:git
  script:
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
    - docker run --rm -i -v ~/.ssh/id_rsa:/root/.ssh/id_rsa -v ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub -v `pwd`/ansible:/ansible/playbooks "$CI_REGISTRY_IMAGE_debian:latest" ansible-playbook -vvv -c local -i /ansible/playbooks/hosts/local /ansible/playbooks/divona.yml --extra-vars="user=root"
  only:
    - master
    - develop
