# Copyright (C) 2013-2017 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

stages:
  - lint
  - configure
  - test

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  ANSIBLE_VERSION: 2.4.0.0
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"

cache:
  paths:
    - .pip/
    - virtenv/

before_script:
  - pip3.6 install virtualenv
  - virtualenv virtenv
  - source virtenv/bin/activate

# ================================
# lint

lint:debug:
  stage: lint
  image: python:3.6
  script:
    - pip install ansible molecule
    - cd debug && molecule lint

lint:setup:
  stage: lint
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd debug && molecule lint

lint:base:
  stage: lint
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd base && molecule lint

lint:wm:
  stage: lint
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd wm && molecule lint

lint:desktop:
  stage: lint
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd desktop && molecule lint

lint:editors:
  stage: lint
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd editors && molecule lint

lint:finish:
  stage: lint
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd finish && molecule lint

lint:cloud:
  stage: lint
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd cloud && molecule lint

# ================================
# CONFIGURE

configure:debug:
  stage: configure
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd debug
    - molecule --debug destroy
    - molecule dependency
    - molecule create
    - molecule prepare

configure:setup:
  stage: configure
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd setup
    - molecule destroy
    - molecule dependency
    - molecule create
    - molecule prepare

configure:base:
  stage: configure
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd base
    - molecule destroy
    - molecule dependency
    - molecule create
    - molecule prepare

configure:wm:
  stage: configure
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd wm
    - molecule destroy
    - molecule dependency
    - molecule create
    - molecule prepare

configure:desktop:
  stage: configure
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd desktop
    - molecule destroy
    - molecule dependency
    - molecule create
    - molecule prepare

configure:editors:
  stage: configure
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd editors
    - molecule destroy
    - molecule dependency
    - molecule create
    - molecule prepare

configure:finish:
  stage: configure
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd finish
    - molecule destroy
    - molecule dependency
    - molecule create
    - molecule prepare

configure:cloud:
  stage: configure
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd cloud
    - molecule destroy
    - molecule dependency
    - molecule create
    - molecule prepare

# ================================
# TEST

test:debug:
  stage: test
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd debug
    - molecule converge
    - molecule idempotence
    - molecule side_effect
    - molecule verify
    - molecule destroy

test:setup:
  stage: test
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd setup
    - molecule converge
    - molecule idempotence
    - molecule side_effect
    - molecule verify
    - molecule destroy

test:base:
  stage: test
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd base
    - molecule converge
    - molecule idempotence
    - molecule side_effect
    - molecule verify
    - molecule destroy

test:wm:
  stage: test
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd wm
    - molecule converge
    - molecule idempotence
    - molecule side_effect
    - molecule verify
    - molecule destroy

test:desktop:
  stage: test
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd desktop
    - molecule converge
    - molecule idempotence
    - molecule side_effect
    - molecule verify
    - molecule destroy

test:editors:
  stage: test
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd editors
    - molecule converge
    - molecule idempotence
    - molecule side_effect
    - molecule verify
    - molecule destroy

test:finish:
  stage: test
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd finish
    - molecule converge
    - molecule idempotence
    - molecule side_effect
    - molecule verify
    - molecule destroy

test:cloud:
  stage: test
  image: python:3.6
  script:
    - pip install ansible molecule docker
    - cd cloud
    - molecule converge
    - molecule idempotence
    - molecule side_effect
    - molecule verify
    - molecule destroy

