# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Base provisionning
  hosts: all
  tags:
    - base
  vars_files:
    - ./env_vars/{{ env }}/all.yml
    - ./env_vars/{{ env }}/base.yml
    - ./env_vars/{{ env }}/editors.yml
  roles:
    - divona.mac.base
    - divona.mac.wm
    - divona.mac.desktop
    - divona.mac.editors
    - divona.mac.cloud
    - divona.mac.finish
    - gantsign.golang
    - hurricanehrndz.rustup
  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      ansible.builtin.stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      ansible.builtin.fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Installing Homebrew
      ansible.builtin.shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing
