# Copyright (C) 2013-2018 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Install distribution tools
  pacman:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - pacman-contrib

- name: Install shell tools
  pacman:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - bash-completion
      - tree
      - tmux
      - ncdu
      - feh

- name: Install terminal emulators
  pacman:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - termite
      - kitty
      - terminator

- name: Install defaults packages
  pacman:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - man-db
      - dunst
      - git
      - gnupg
      - tig
      - unzip
      - ccze

- name: Install networks tools
  pacman:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - dhclient
      - openssh
      - wget
      - curl
      - bind-tools
      - mtr
      - traceroute
      - openbsd-netcat
      - ipcalc
      - nmap
      - ngrep
      - nethogs

- name: Install modern Unix tools
  pacman:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - fzf
      - ripgrep
      - exa
      - fd
