# Copyright (C) 2013-2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Install Powerline-Go CLI
  # when:
  #   - powerling_go_installation_required
  get_url:
    url: "{{ powerline_go_linux_download_url }}"
    dest: "{{ powerline_go_linux_file }}"
    mode: 0755
    force: true

- name: Check LF installation
  command: which lf
  register: lf_installation
  changed_when: false
  ignore_errors: true
  check_mode: false

- name: Get installed LF version
  command: "{{ lf_installation.stdout }} -version"
  when: not lf_installation is failed
  changed_when: false
  check_mode: false
  register: installed_lf_version

- name: LF installation is required
  set_fact:
    lf_installation_required: "{{ lf_installation is failed or installed_lf_version.stdout != lf_version }}"

- name: LF installation
  when:
    - lf_installation_required
  block:
    - name: Download LF archive
      get_url:
        url: "{{ lf_linux_download_url }}"
        dest: "/tmp/{{ lf_linux_package_name }}"
        mode: 0600
        # checksum: "{{ lf_linux_checksum }}"
        force: true

    - name: Install LF
      unarchive:
        src: "/tmp/{{ lf_linux_package_name }}"
        dest: "{{ lf_linux_dir }}"

- name: Check Gotop installation
  command: which gotop
  register: gotop_installation
  changed_when: false
  ignore_errors: true
  check_mode: false

- name: Get installed Gotop version
  command: "{{ gotop_installation.stdout }} --version"
  when: not gotop_installation is failed
  changed_when: false
  check_mode: false
  register: installed_gotop_version

- name: Gotop installation is required
  set_fact:
    gotop_installation_required: "{{ gotop_installation is failed or installed_gotop_version.stdout != gotop_version }}"

- name: Gotop installation
  when:
    - gotop_installation_required
  block:
    - name: Download Gotop archive
      get_url:
        url: "{{ gotop_linux_download_url }}"
        dest: "/tmp/{{ gotop_linux_package_name }}"
        mode: 0600
        # checksum: "{{ gotop_linux_checksum }}"
        force: true

    - name: Install Gotop
      unarchive:
        src: "/tmp/{{ gotop_linux_package_name }}"
        dest: "{{ gotop_linux_dir }}"

- name: Check Lazygit installation
  command: which lazygit
  register: lazygit_installation
  changed_when: false
  ignore_errors: true
  check_mode: false

- name: Get installed Lazygit version
  shell: |
    set -o pipefail
    {{ lazygit_installation.stdout }} -v|awk -F',' '{ print $4 }'|awk -F'=' '{ print $2 }'
  when: not lazygit_installation is failed
  changed_when: false
  check_mode: false
  register: installed_lazygit_version

- name: Lazygit installation is required
  set_fact:
    lazygit_installation_required: "{{ lazygit_installation is failed or installed_lazygit_version.stdout != lazygit_version }}"

- name: Lazygit installation
  when:
    - lazygit_installation_required
  block:
    - name: Download Lazygit archive
      get_url:
        url: "{{ lazygit_linux_download_url }}"
        dest: "/tmp/{{ lazygit_linux_package_name }}"
        mode: 0600
        checksum: "{{ lazygit_linux_checksum }}"
        force: true

    - name: Install Lazygit
      unarchive:
        src: "/tmp/{{ lazygit_linux_package_name }}"
        dest: "{{ lazygit_linux_dir }}"
