# Copyright (C) 2013-2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# - name: Add the user
#   user:
#     name: "{{ user }}"
#     shell: /bin/bash
#     groups: users
#     append: true

# - name: Ensure group exists
#   group:
#     name: "{{ user }}"
#     state: present

- name: Create Applications directory
  file:
    path: /home/{{ user }}/Applications
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory
    mode: 0755

- name: Create user binary directory
  file:
    path: /home/{{ user }}/bin
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory
    mode: 0755

- name: Create user configuration directory
  file:
    path: /home/{{ user }}/etc
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory
    mode: 0755

- name: Create Work directory
  file:
    path: /home/{{ user }}/Work
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory
    mode: 0755

- name: Create own projects directory
  file:
    path: /home/{{ user }}/Projects
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory
    mode: 0755

- name: Create Documents directory
  file:
    path: /home/{{ user }}/Documents
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory
    mode: 0755
