# Copyright (C) 2013-2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Install X
  pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libglvnd
      - xorg-server
      - xorg-xinit
      - arandr
      - slim
      - slim-themes
      - archlinux-themes-slim
      # - lxdm
      # - lxdm-gtk3
      - sddm
      - lightdm
      - lightdm-gtk-greeter-settings
      - lightdm-webkit2-greeter
      - light-locker

# - name: Install themes
#   pacman:
#     name: "{{ packages }}"
#     state: present
#   vars:
#     packages:
#       - arc-gtk-theme
#       - adapta-gtk-theme

- name: Install web browsers
  pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - chromium
      # - brave

- name: Install graphics applications
  pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gimp
      - inkscape
      - flameshot

- name: Install video applications
  pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vlc

- name: Install music applications
  pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - pulseaudio
      - pavucontrol
      - pulsemixer
      - playerctl

- name: Install communications applications
  pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - irssi
      - vinagre
      - rdesktop

- name: Install documentation applications
  pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - evince
      - mupdf

- name: Install fonts
  pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - awesome-terminal-fonts
      # - ttf-symbola

- name: Install security tools
  pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openvpn
      - wireguard-tools
      - wireguard-arch
      - keepassxc
      - arch-audit

- name: Install clipboard tools
  pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - clipmenu
      - clipnotify
