# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :dev do |debian_config|
    debian_config.vm.box = "debian-squeeze-amd64"
    debian_config.vm.box_url = "https://dl.dropbox.com/u/1543052/Boxes/DebianSqueeze64.box"

    debian_config.vm.hostname = "LamDebian"
    debian_config.vm.network :private_network, :ip => '10.1.2.41'

    debian_config.ssh.forward_agent = true
    debian_config.ssh.forward_x11 = true

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    # config.vm.synced_folder "../data", "/vagrant_data"

    debian_config.vm.provider :virtualbox do |vb|
      #vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.name = "NimbusDebian"
    end

    debian_config.vm.provision :puppet do |puppet|
      puppet.manifests_path = "../../puppet/manifests"
      puppet.manifest_file = "default.pp"
      puppet.module_path = "../../puppet/modules"
      puppet.options = "--verbose --debug"
    end

  end

end
