# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :netbsd do |netbsd_config|
    netbsd_config.vm.box = "nlamirault/netbsd-7.0"

    netbsd_config.vm.hostname = "DivonaNetBSDDev"
    netbsd_config.vm.network :private_network, :ip => '10.10.5.33'

    netbsd_config.ssh.insert_key = false
    # netbsd_config.ssh.private_key_path = "./vagrant.pub"
    netbsd_config.ssh.forward_agent = true
    netbsd_config.ssh.forward_x11 = true

    netbsd_config.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.name = "DivonaNetBSDDev"
    end

    netbsd_config.vm.provision :ansible do |ansible|
      ansible.playbook = "../../ansible/divona.yml"
      ansible.inventory_path = "./host"
      ansible.limit = "all"
      ansible.verbose = 'vvvv'
      ansible.host_key_checking = false
    end

    netbsd_config.vm.provision :ansible do |ansible|
      ansible.playbook = "../../ansible/dev.yml"
      ansible.inventory_path = "./host"
      ansible.limit = "all"
      ansible.verbose = 'vvvv'
      ansible.host_key_checking = false
    end

  end

end
