# -*- mode: ruby -*-
# vi: set ft=ruby :

# Copyright (C) 2013-2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Copyright (C) 2013-2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
Vagrant.configure("2") do |config|

  config.vm.define :netbsd do |netbsd_config|
    netbsd_config.vm.box = "nlamirault/netbsd-7.0"

    netbsd_config.vm.hostname = "DivonaNetBSDDev"
    netbsd_config.vm.network :private_network, :ip => '10.10.5.33'

    netbsd_config.ssh.insert_key = false
    # netbsd_config.ssh.private_key_path = "./vagrant.pub"
    netbsd_config.ssh.forward_agent = true
    netbsd_config.ssh.forward_x11 = true

    netbsd_config.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.name = "DivonaNetBSDDev"
    end

    netbsd_config.vm.provision :ansible do |ansible|
      ansible.playbook = "../../ansible/divona.yml"
      ansible.inventory_path = "./host"
      ansible.limit = "all"
      ansible.verbose = 'vvvv'
      ansible.host_key_checking = false
    end

    netbsd_config.vm.provision :ansible do |ansible|
      ansible.playbook = "../../ansible/dev.yml"
      ansible.inventory_path = "./host"
      ansible.limit = "all"
      ansible.verbose = 'vvvv'
      ansible.host_key_checking = false
    end

  end

end
