---
# Divona
- name: divona.bootstrap
  src: git@github.com:divona-roles/ansible-bootstrap-role.git
  scm: git
  version: v1.0.0
- name: divona.motd
  src: git@github.com:divona-roles/ansible-motd-role.git
  scm: git
  version: v1.0.0
- name: divona.debug
  src: git@github.com:divona-roles/ansible-debug-role.git
  scm: git
  version: v1.0.0
- name: divona.base
  src: git@github.com:divona-roles/ansible-base-role.git
  scm: git
  version: v2.0.0
- name: divona.desktop
  src: git@github.com:divona-roles/ansible-desktop-role.git
  scm: git
  version: v1.0.0
- name: divona.editors
  src: git@github.com:divona-roles/ansible-editors-role.git
  scm: git
  version: v2.1.0
- name: divona.languages
  src: git@github.com:divona-roles/ansible-languages-role.git
  scm: git
  version: v1.0.0
- name: divona.cloud
  src: git@github.com:divona-roles/ansible-cloud-role.git
  scm: git
  version: v0.1.0
- name: divona.wm
  src: git@github.com:divona-roles/ansible-window-managers-role.git
  scm: git
  version: v1.0.0
- name: divona.finish
  src: git@github.com:divona-roles/ansible-finish-role.git
  scm: git
  version: v1.0.0

# External
# ========================================
- src: markosamuli.asdf
  version: v1.1.0
