# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :divona do |divona_config|
    divona_config.vm.box = "archlinux"
    divona_config.vm.box_url = "https://dl.dropboxusercontent.com/u/31112574/arch64-20130801.box"
    divona_config.vm.hostname = "DivonaArch"

    divona_config.vm.network :private_network, :ip => '10.10.2.33'
    # Assign this VM to a host-only network IP, allowing you to access it
    # via the IP. Host-only networks can talk to the host machine as well as
    # any other machines on the same network, but cannot be accessed (through this
    # network interface) by any external networks.
    # divona_config.vm.network :hostonly, "172.16.0.201"
    # divona_config.vm.network :hostonly, "10.10.0.201"

    divona_config.ssh.forward_agent = true
    divona_config.ssh.forward_x11 = true

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    # config.vm.synced_folder "../data", "/vagrant_data"

    divona_config.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.name = "DivonaArch"
    end

    divona_config.vm.provision :ansible do |ansible|
      ansible.playbook = "../../ansible/setup.yml"
      ansible.inventory_path = "../../ansible/vagrant_hosts"
      ansible.verbose = '-vv'
    end

  end

end
