# Copyright (C) 2013-2018 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install window manager
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - i3-wm
    - i3status
    - i3lock
    - dmenu
    - rofi
    - openbox
    - openbox-themes
    - obconf
    - obmenu
    - conky
    - thunar
    - thunar-volman
    - thunar-archive-plugin
    - tint2
    - xautolock

- name: Install XFCE
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - xfce4
    # - xfce4-goodies
    - xfce4-notifyd
