# Copyright (C) 2013-2018 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Install Packer
  homebrew:
    name: packer
    state: latest

- name: Install Terraform
  homebrew:
    name: terraform
    state: latest

- name: Install Vault
  homebrew:
    name: vault
    state: latest

- name: Install Kubernetes CLI
  homebrew:
    name: kubernetes-cli
    state: latest

- name: Install Minikube
  get_url:
    url: "{{ minikube_darwin_download_url }}"
    dest: "{{ minikube_darwin_file }}"
    mode: 0755

- name: Install GCloud SDK
  unarchive:
    src: "{{ gcloud_sdk_darwin_download_url }}"
    dest: "{{ gcloud_sdk_darwin_dir }}"
    remote_src: true

- name: Adding GCloud command to user path
  file:
    src: "{{ gcloud_sdk_darwin_dir }}/google-cloud-sdk/bin/gcloud"
    dest: /Users/{{ user }}/bin/gcloud
    state: link

- name: Install Istio
  unarchive:
    src: "{{ istio_darwin_download_url }}"
    dest: "{{ istio_dir }}"
    remote_src: true

- name: Adding Istio command to user path
  file:
    src: "{{ istio_dir }}/istio-{{ istio_version }}/bin/istioctl"
    dest: /Users/{{ user }}/bin/istioctl
    state: link
