# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :dev do |freebsd_config|
    freebsd_config.vm.box = "freebsd-9.1-amd64"
    freebsd_config.vm.box_url = "https://github.com/downloads/xironix/freebsd-vagrant/freebsd_amd64_ufs.box"

    freebsd_config.vm.hostname = "LamFreeBSD"
    freebsd_config.vm.network :private_network, :ip => '10.1.2.42'

    freebsd_config.ssh.forward_agent = true
    freebsd_config.ssh.forward_x11 = true

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    # config.vm.synced_folder "../data", "/vagrant_data"

    freebsd_config.vm.provider :virtualbox do |vb|
      #vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.name = "LamFreeBSD"
    end

    # freebsd_config.vm.provision :puppet do |puppet|
    #   puppet.manifests_path = "../../puppet/manifests"
    #   puppet.manifest_file = "default.pp"
    #   puppet.module_path = "../../puppet/modules"
    #   puppet.options = "--verbose --debug"
    # end

  end

end
