#
# Desktop settings for Arch
#
#

- name: Install web applications
  pacman: name={{ item }} state=installed
  with_items:
    - chromium
    - midori

- name: Install graphics applications
  pacman: name={{ item }} state=installed
  with_items:
    - gimp
    - inkscape
    - evince
    - vlc

- name: Install communications applications
  pacman: name={{ item }} state=installed
  with_items:
    - irssi
    - vinagre
    - rdesktop
