# Copyright (C) 2013-2018 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Desktop settings for Arch
#


- name: Install X
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - libglvnd
    - xorg-server
    - xorg-xinit
    - slim
    - slim-themes
    - archlinux-themes-slim
    # - lxdm
    # - lxdm-gtk3
    - sddm
    - lightdm
    - lightdm-gtk-greeter-settings

- name: Install themes
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - arc-gtk-theme
    - adapta-gtk-theme

- name: Install web applications
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - chromium
    # - qutebrowser

- name: Install multimedia applications
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - gimp
    - inkscape

- name: Install video applications
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - vlc

- name: Install communications applications
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - irssi
    - vinagre
    - rdesktop

- name: Install documentation applications
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - evince

- name: Install fonts
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - awesome-terminal-fonts
    - ttf-symbola

- name: Install security tools
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - keepassxc
    - arch-audit
