#
# Desktop settings for Arch
#
#

- name: Install web applications
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - chromium
    # - qutebrowser

- name: Install multimedia applications
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - gimp
    - inkscape

- name: Install video applications
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - vlc

- name: Install communications applications
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - irssi
    - vinagre
    - rdesktop

- name: Install documentation applications
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - evince

- name: Install awesome-terminal-fonts
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - awesome-terminal-fonts

- name: Install Feed readers
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - newsbeuter

- name: Install security tools
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - keepassxc
