- name: Install xinitrc
  copy: src=xinitrc dest=/home/{{ user }}/.xinitrc

- name: Install bashrc
  copy: src=bashrc dest=/home/{{ user }}/.bashrc

- name: Install profile
  copy: src=bash_profile dest=/home/{{ user }}/.bash_profile

- name: Install environmentrc
  copy: src=environmentrc dest=/home/{{ user }}/.environmentrc

- name: Install gitconfig
  copy: src=gitconfig dest=/home/{{ user }}/.gitconfig

- name: Install inputrc
  copy: src=inputrc dest=/home/{{ user }}/.inputrc

- name: Install tmuxconf
  copy: src=tmux.conf dest=/home/{{ user }}/.tmux.conf

- name: Install vimrc
  copy: src=vimrc dest=/home/{{ user }}/.vimrc

- name: Create Applications directory
  command: mkdir /home/{{ user }}/Apps creates=/home/{{ user }}/Apps
