#
# Desktop settings for OSX
#
#

- name: Install web applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - chromium

- name: Install graphics applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - gimp

- name: Install video applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - vlc
    - iina

- name: Install communications applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - hexchat
