# Copyright (C) 2013-2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# - name: Default to list view in Finder
#   command: defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# - name: Shows path in titleBar
#   command: "defaults write com.apple.finder _FXShowPosixPathInTitle -bool true"

# - name: New window opens home directory
#   command: defaults write com.apple.finder NewWindowTarget -string "PfHm"

# - name: Show hidden files
#   command: "defaults write com.apple.finder AppleShowAllFiles -bool YES"

# - name: Enable dock autohide
#   command: defaults write com.apple.dock autohide -bool false

# - name: Remove dock autohide delay
#   command: defaults write com.apple.dock autohide-delay -float 0

# - name: Quicken animation when showing/hiding dock
#   command: defaults write com.apple.dock autohide-time-modifier -float 0

# - name: Set dock icon size
#   command: defaults write com.apple.dock tilesize -int 40

# - name: Change the min/max window effect to scale
#   command: defaults write com.apple.dock mineffect -string "scale"

# - name: Disable dock magnification
#   command: defaults write com.apple.dock magnification -bool true

# - name: Bottom align dock position
#   command: defaults write com.apple.dock orientation -string bottom

# - name: Empty dock of applications
#   command: defaults write com.apple.dock persistent-apps -array

# - name: Add specific applications to dock
#   command: defaults write com.apple.dock persistent-apps -array-add "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>{{ item }}</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>"
#   with_items:
#     - "/Applications/System Preferences.app"
#     - "/Applications/App Store.app"
#     - "/Users/{{ user }}/Applications/Google Chrome.app"
#     - "/Applications/Safari.app"
#     - "/Applications/iTunes.app"
#     - "/Users/{{ user }}/Applications/iTerm.app"

# - name: Empty dock of folders
#   command: defaults write com.apple.dock persistent-others -array

# - name: Add specific folders to dock
#   command: defaults write com.apple.dock persistent-others -array-add "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>{{ item }}</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>"
#   with_items:
#     - "/Users/{{ user }}/Documents"
#     - "/Users/{{ user }}/Projects"
#     - "/Users/{{ user }}/Applications"

- name: Install windows manager
  homebrew:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - koekeishiya/formulae/kwm

- name: Install windows manager
  homebrew_cask:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - amethyst
