# Copyright (C) 2013-2018 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Window Manager for Debian
  include_tasks: debian_init.yml
  when: ansible_distribution == 'Debian'
  become: true
  become_user: root

- name: Window Manager for Arch Linux
  include_tasks: arch_init.yml
  when: ansible_distribution == 'Arch Linux'
  become: true
  become_user: root

- name: Window Manager for CentOS
  include_tasks: centos_init.yml
  when: ansible_distribution == 'CentOS'
  become: true
  become_user: root

- name: Base for Fedora
  import_tasks: fedora_init.yml
  when: ansible_distribution == 'Fedora'
  become: true
  become_user: root

- name: Window Manager for FreeBSD
  include_tasks: freebsd_init.yml
  when: ansible_distribution == 'FreeBSD'
  become: true
  become_user: root

- name: Window Manager for NetBSD
  include_tasks: netbsd_init.yml
  when: ansible_distribution == 'NetBSD'
  become: true
  become_user: root

- include_tasks: openbsd.yml
  when: ansible_distribution == 'OpenBSD'
  become: true
  become_user: root

- include_tasks: osx_init.yml
  when: ansible_distribution == 'MacOSX'
