;;; Emacs Cask file

(source "melpa" "http://melpa.milkbox.net/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")

;; Misc
(depends-on "cask")
(depends-on "auto-complete")
(depends-on "markdown-mode")
(depends-on "sr-speedbar")
(depends-on "yaml-mode")
(depends-on "flycheck")

;; Go lang
(depends-on "go-mode")
(depends-on "go-play")
(depends-on "go-autocomplete")
(depends-on "go-eldoc")
(depends-on "flymake-go")

;; Python
(depends-on "python-mode")
(depends-on "jedi")
(depends-on "elpy")
(depends-on "tox")
(depends-on "virtualenvwrapper")
(depends-on "flymake-python-pyflakes")

;; Ruby
(depends-on "ruby-mode")

;; Web
(depends-on "web-mode")
(depends-on "php-mode")
(depends-on "flymake-php")

;; Other development mode

;; Cloud
(depends-on "dockerfile-mode")
(depends-on "vagrant")
(depends-on "puppet-mode")

;; Utilities
(depends-on "pkg-info")
(depends-on "magit")
(depends-on "projectile")
(depends-on "helm")
(depends-on "helm-projectile")
(depends-on "project-persist")
(depends-on "helm-project-persist")
(depends-on "multi-term")
(depends-on "project-explorer")
(depends-on "prodigy")

;; UI
(depends-on "smart-mode-line")
(depends-on "diminish")
(depends-on "powerline")
(depends-on "direx")


;; Mail
;;(depends-on "mu4e")
(depends-on "w3m")
(depends-on "offlineimap")

;; Organisation
(depends-on "org")
(depends-on "google-weather")
(depends-on "weather-metno")
;;(depends-on "org-jira")

;; UI
(depends-on "smart-mode-line")
