- name: VIM directory
  action: file path=/Users/{{ user }}/.vim state=directory

- name: VIM Bundle directory
  action: file path=/Users/{{ user }}/.vim/bundle state=directory

- name: VIM Vundle
  git: repo=https://github.com/gmarik/vundle.git dest=/home/{{ user }}/.vim/bundle/vundle
