# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.hostname = "LamDevUbuntu"
  config.vm.network :private_network, ip: "10.1.1.33"

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
  
  config.vm.provider :virtualbox do |vb|
    #vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.name = "LamDevUbuntu"
  end
          
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "../../../puppet/manifests"
    puppet.manifest_file = "default.pp"
    puppet.module_path = "../../../puppet/modules"
    puppet.options = "--verbose --debug"
  end

end
