- name: User in Docker group
  user: name={{ user }} groups=docker append=yes

- name: Docker service enable
  service: name={{item}} state=started
  with_items:
    - docker

- name: Verify Packer archive
  stat: path=/home/{{ user }}/Apps/packer_{{ packer_version }}_linux_amd64.zip
  register: packer_archive

- name: Install Packer
  get_url: url=https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip dest=/home/{{ user }}/Apps/packer_{{ packer_version }}_linux_amd64.zip mode=0440
  when: packer_archive.stat is not defined

- name: Verify Terraform archive
  stat: path=/home/{{ user }}/Apps/terraform_{{ terraform_version }}_linux_amd64.zip
  register: terraform_archive

- name: Install Terraform
  get_url: url=https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip dest=/home/{{ user }}/Apps/terraform_{{ terraform_version }}_linux_amd64.zip mode=0440
  when: terraform_archive.stat is not defined
