---
- name: Install Docker requirements
  apt: pkg={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: docker apt-key present
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: docker repo present
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
    filename: 'docker'
    state: present

- name: apt-get update
  apt:
    update_cache: yes

- name: docker-engine present
  apt:
    name: "docker-ce"
    state: present
    force: true

- name: Download Rkt
  get_url: >
   url=https://github.com/coreos/rkt/releases/download/v{{ rkt_version }}/rkt-v{{ rkt_version }}.tar.gz
   dest=/tmp/rkt.zip

- name: Extract Rkt
  unarchive: >
   src=/tmp/rkt.zip
   dest=/srv/
   copy=no
   owner={{ ansible_ssh_user }}

- name: Oracle Virtualbox public key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Third-party repo present
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian stretch contrib"
    filename: 'contrib'
    state: present

- name: apt-get update
  apt:
    update_cache: yes

- name: Install Virtualbox
  apt: pkg={{ item }} state=present
  with_items:
    - virtualbox-5.1

- name: Verify Vagrant deb file
  stat: path=/home/{{ user }}/Apps/vagrant_{{ vagrant_version }}_x86_64.deb
  register: vagrant_debfile

- name: Download Vagrant
  get_url: url=https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb dest=/home/{{ user }}/Apps/vagrant_{{ vagrant_version }}_x86_64.deb mode=0440
  when: vagrant_debfile.stat.exists == False
