---
- include_tasks: debian.yml
  become: true
  become_user: root
  when: ansible_distribution == 'Debian'
- include_tasks: arch.yml
  become: true
  become_user: root
  when: ansible_distribution == 'Arch Linux'
#- include_tasks: freebsd.yml
#  become: true
#  become_user: root
#  when: ansible_distribution == 'FreeBSD'
- include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'
  become: true
  become_user: root

- include_tasks: linux.yml
  when: (ansible_distribution == 'Arch Linux' or
         ansible_distribution == 'Debian' or
         ansible_distribution == 'CentOS')
- include_tasks: osx.yml
  when: ansible_distribution == 'Darwin'
- include_tasks: win.yml
  when: ansible_distribution == 'Windows'
- include_tasks: cloud_linux.yml
  when: (ansible_distribution == 'Arch Linux' or
         ansible_distribution == 'Debian' or
         ansible_distribution == 'CentOS')
  become: true
  become_user: root
- include_tasks: cloud_osx.yml
  when: ansible_distribution == 'Darwin'
- include_tasks: cloud_win.yml
  when: ansible_distribution == 'Windows'
