- stat: path=C:\Apps\go1.6.2.windows-amd64.msi
  register: golang_archive

- name: Download Golang
  get_url: url=https://storage.googleapis.com/golang/go1.6.2.windows-amd64.msi dest=C:\Apps\go1.6.2.windows-amd64.msi mode=0440
  when: golang_archive.stat is not defined

- stat: path=C:\Apps\rust-1.9.0-x86_64-pc-windows-gnu.msi
  register: rust_archive

- name: Download Rust
  get_url: url=https://static.rust-lang.org/dist/rust-1.9.0-x86_64-pc-windows-gnu.msi dest=C:\Apps\rust-1.9.0-x86_64-pc-windows-gnu.msi mode=0440
  when: rust_archive.stat is not defined

- stat: path=C:\Apps\node-v6.2.1-x64.msi
  register: node_archive

- name: Download NodeJS
  get_url: url=https://nodejs.org/dist/v6.2.1/node-v6.2.1-x64.msi dest=C:\Apps\node-v6.2.1-x64.msi mode=0440
  when: node_archive.stat is not defined
